### ISSUE TITLE
Support for GFPGAN?

### ISSUE THREAD

**Issue by AIisCool** [rlaphoenix/VSGAN#11]
First off thank you for VSGAN!

I was trying to see the results of this model: https://github.com/TencentARC/GFPGAN/releases/download/v0.2.0/GFPGANCleanv1-NoCE-C2.pth from https://github.com/TencentARC/GFPGAN but received this error: 'model.0.weight'.

Is this model set incompatible or is there some other issue? Thank you.

**Comment by rlaphoenix** [comment]
That is a model for GFPGAN, not ESRGAN. VSGAN currently only supports ESRGAN at the time of writing.

**Comment by rlaphoenix** [comment]
Support for GFPGAN most likely won't happen, at least not soon. This project is focused on general image and video inputs, but GFPGAN is focused specifically on faces. You need to crop the images to only the faces for it to really work.
