### ISSUE TITLE
VSGAN does not return a clip

### ISSUE THREAD

**Issue by styler00dollar** [rlaphoenix/VSGAN#12]
```
clip = vs.core.resize.Bicubic(clip, width=848, height=480, format=vs.RGBS, matrix_in_s='709')
clip = VSGAN(clip, device="cuda").load_model("model.pth").run(overlap=16)
clip = vs.core.resize.Bicubic(clip, format=vs.YUV420P8, matrix_s="709")
```
```
vapoursynth.Error: Bicubic: argument clip was passed an unsupported type (expected vnode compatible type but got VSGAN)
```

https://github.com/rlaphoenix/VSGAN/blob/3a894f3f7cf2e0ea1dca834d4234f1a9087762e3/vsgan/__init__.py#L113
Change this to `return self.clip`, to return the clip and it will work again.

**Comment by rlaphoenix** [comment]
Doing `return self.clip` won't work as we will not then be able to access the other functions of VSGAN class.

Your mistake is not doing a `.clip` at the end of the call, after `.run(...)`

**Comment by styler00dollar** [comment]
Seems like i overlooked `.clip` and this would be a workaround to fix that. Thanks.
