### ISSUE TITLE
Add Vulkan Support

### ISSUE THREAD

**Issue by LuisB79** [rlaphoenix/VSGAN#14]
RealESRGAN can use vulkan for amd support, and maybe other models.
https://github.com/xinntao/Real-ESRGAN

**Comment by rlaphoenix** [comment]
I do not have any form of method to test anything AMD-related, and I do not know the environment of Vulkan/AMD PyTorch well enough to know how to do this. But, with a bit of research, it seems to need a few separate dependencies and a specific device name of which some may or may not support some model architectures.

Hopefully someone who sees VSGAN, knows PyTorch, and is an AMD user pops by one day and can provide some help.

**Comment by LuisB79** [comment]
Closing the issue, if you wish, post the help wanted in the main page.

**Comment by rlaphoenix** [comment]
There is no need to close this considering its still open for discussion.

**Comment by LuisB79** [comment]
Closing this since vs-mlrt supports vulkan.

**Comment by rlaphoenix** [comment]
But my project doesn't, so I'm reopening it.

**Comment by LuisB79** [comment]
> But my project doesn't, so I'm reopening it.
Write a message on the main page asking for Vulkan support, or create another issue.

**Comment by rlaphoenix** [comment]
Please stop closing this. It's being kept open.

**Comment by LuisB79** [comment]
Delete the issue, else i'll continue to close it.

**Comment by rlaphoenix** [comment]
You're one annoying guy my dude. The entire point of the issue is to signal that Vulkan needs support. I do not want a duplicate issue. You cannot just delete issues. Even if I could, it's still hella annoying.

Please refrain from making any more issues in the future, at all.
