### ISSUE TITLE
Crashing with v1.6.0

### ISSUE THREAD

**Issue by AIisCool** [rlaphoenix/VSGAN#16]
`import vapoursynth as vs`
`from vapoursynth import core`
`core = vs.core`

`#Source`
`clip = core.avisource.AVISource(r'C:/Users/MainUser/Desktop/Videos/MP4s/S6xE04.avs')`
`clip = core.resize.Point(clip=clip, format=vs.YUV422P16, matrix_s="470bg")`

`#Trim`
`clip = core.std.Trim(clip, 7348,7355)`

`#RGBS`
`clip = core.resize.Point(clip=clip, format=vs.RGBS, matrix_s="470bg")`

`from vsgan import ESRGAN`
`clip = ESRGAN(clip, device="cuda").\`
`load(r"C:\VapourSynth\vsgan_models\BSRGAN.pth").\`
`apply(overlap=16).\`
`clip`

`#YUV422P16`
`clip = core.resize.Point(clip=clip, format=vs.YUV422P16, matrix_s="470bg")`
`#OUTPUT`
`clip.set_output()`

Very excited to try out v1.6.0, but while this worked for v1.5.0 (barring changing a few things for v1.6.0), it's causing VirtualDub2 to crash immediately (`An out-of-bounds memory access (access violation) occurred at 7ffaa617e771...
...reading address 0000000000000048.`) which generally only happened when I had too many functions called when using v1.5.0 . I also tried with VSPipe and it's failing as well.

I reviewed everything and I'm honestly not sure why it's not working. Using Python 3.9.7 and VapourSynth (64-bit) R57.

**Comment by rlaphoenix** [comment]
Oops! I missed an `overlap` specification for join_tiles from within recursive_tile_tensor.
https://github.com/rlaphoenix/VSGAN/commit/a7025a38f52ab6d9af3e583d0d3bb5cc5f76e4fd

I'll release a 1.6.1 patch asap.

**Comment by rlaphoenix** [comment]
Should be fully fixed as of v1.6.2, had two regressions in the end (oops). Also, you should really ditch VirtualDub2 for VapourSynth-Editor mod: https://github.com/YomikoR/VapourSynth-Editor

**Comment by AIisCool** [comment]
Yes that fixed it! I was quite puzzled as to what I could've done wrong. I'll look into VapourSynth-Editor mod.

Not sure if it's worth opening a new issue, but I've found that if I have `load(r"C:\VapourSynth\vsgan_models\BSRGAN.pth", half=True)` it crashes again? I tested it with `load(r"C:\VapourSynth\vsgan_models\BSRGAN.pth", half=False)` and no crash.
