### ISSUE TITLE
half=True - causing crashes?

### ISSUE THREAD

**Issue by AIisCool** [rlaphoenix/VSGAN#17]
Sorry to be  a bother, but I've found that if I have `load(r"C:\VapourSynth\vsgan_models\BSRGAN.pth", half=True)` it crashes. I tested it with `load(r"C:\VapourSynth\vsgan_models\BSRGAN.pth", half=False)` and no crash. Tested with a few other ESRGAN models and same deal with "True" crashing and "False" not crashing.

**Comment by rlaphoenix** [comment]
Fixed in v1.6.3, yet another blunder from 1.6.0. This time it was because the rejoined tiling system would create the new merged tile under the default device (99% of setups would have this to be the CPU).
