### ISSUE TITLE
GUI for VSGAN?

### ISSUE THREAD

**Issue by rayman3003** [rlaPHOENiX/VSGAN#2]
I searched for a GUI on github, But couldn't find any.

Is it possible to have a GUI for VSGAN?

**Comment by rlaPHOENiX** [comment]
VSGAN isnt a tool that the user interacts with directly, you use VSGAN using VapourSynth.
Take a look at https://github.com/rlaPHOENiX/VSGAN/wiki/Usage

VapourSynth does have a GUI named VapourSynth-Editor which can be found here:
https://forum.doom9.org/showthread.php?t=170965

**Comment by mirh** [comment]
There is technically, but it still would require a bit of a setup
https://forum.selur.net/thread-1935.html
