### ISSUE TITLE
yuuno requires python >= 3.8

### ISSUE THREAD

**Issue by gabgren** [rlaphoenix/VSGAN#28]
The current Colab example fails because the latest version of yuuno is asking for python3.8, colab is python3.7

I solved it by replacing the install yuuno code by:
`!pip install yuuno==1.3.2`

This older version of yuuno installs fine

**Comment by gabgren** [comment]
Yeah, I wanted to post it here just in case other users face the same problem, since I was following the colab notebook from this repo. The first thing I did was to look in this repo's issues to see if it was there. I guess that we could close this issue, or delete it if you think it does not belong here,

 1.3.2 did install properly, not sure why if it requires 3.9, I didn't even verify, I just tried this version and it went through

**Comment by rlaphoenix** [comment]
Since Google Colab uses Python 3.9 now, and VSGAN's minimum supported version is now 3.8, I believe this is no longer an issue.
