### ISSUE TITLE
Torch 2.0 compatible.

### ISSUE THREAD

**Issue by Selur** [rlaphoenix/VSGAN#34]
I'm trying to get Python 3.11 + Vapoursynth R62 + pyTorch + VSGAN working on Windows.
Looking at https://download.pytorch.org/whl/torch/ the only Python 3.11 builds seem to be either Torch 2.0 or for Linux.
=> Does VSGAN work with pyTorch 2.0 or do you know a source for a Python 3.11 compatible pyTorch version for Windows?

**Comment by rlaphoenix** [comment]
Hi Selur,

I'm not sure if PyTorch 2.0 is compatible as I've never tried. Have you given it a shot and see what happens?

**Comment by Selur** [comment]
No, haven't tried it, but I'll test it tomorrow and report back. (I know that some of HolyWus projects do not support PyTorch 2.0, so  I through I might ask before I try. ;))

**Comment by Selur** [comment]
Did test:
- created a new empy Vapoursynth-folder
- downloaded 'Windows embeddable package (64-bit)' from https://www.python.org/downloads/release/python-3111/
- extracted the Python download into the download into the 'Vapoursynth'-folder
- downloaded 'VapourSynth64-Portable-R62' from https://github.com/vapoursynth/vapoursynth/releases
- extracted the Vapoursynth portable download into the 'Vapoursynth'-folder
- downloaded get-pip.py from https://bootstrap.pypa.io/get-pip.py and save it into the 'Vapoursynth'-folder
- opened a 'Windows Command Prompt'-window and navigate into the 'Vaporusynth'-folder
- installed pip by calling `` pyhton get-pip.py`
- opened the python311._pth in a text editor and added the following to lines above anything else in that file and saved the file
```
Scripts
Lib\site-packages
````
- installed Pytoch using: `python -m pip install torch===2.0.0+cu117 torchvision===0.15.1 -f https://download.pytorch.org/whl/torch_stable.html`
- installed VSGAN using: python -m pip install -U VSGAN
- created a Vapoursynth script:
```
# Imports
import vapoursynth as vs
import os
import sys
# getting Vapoursynth core
core = vs.core
# Import scripts folder
scriptPath = 'i:/Hybrid/64bit/vsscripts'
sys.path.insert(0, os.path.abspath(scriptPath))
# Loading Plugins
core.std.LoadPlugin(path="i:/Hybrid/64bit/vsfilters/Support/fmtconv.dll")
core.std.LoadPlugin(path="i:/Hybrid/64bit/vsfilters/SourceFilter/LSmashSource/vslsmashsource.dll")
# Import scripts
import mvsfunc
# source: 'G:\TestClips&Co\test.avi'
# current color space: YUV420P8, bit depth: 8, resolution: 640x352, fps: 25, color matrix: 470bg, yuv luminance scale: limited, scanorder: progressive
# Loading G:\TestClips&Co\test.avi using LWLibavSource
clip = core.lsmas.LWLibavSource(source="G:/TestClips&Co/test.avi", format="YUV420P8", stream_index=0, cache=0, prefer_hw=0)
# Setting detected color matrix (470bg).
clip = core.std.SetFrameProps(clip, _Matrix=5)
# Setting color transfer info (470bg), when it is not set
clip = clip if not core.text.FrameProps(clip,'_Transfer') else core.std.SetFrameProps(clip, _Transfer=5)
# Setting color primaries info (), when it is not set
clip = clip if not core.text.FrameProps(clip,'_Primaries') else core.std.SetFrameProps(clip, _Primaries=5)
# Setting color range to TV (limited) range.
clip = core.std.SetFrameProp(clip=clip, prop="_ColorRange", intval=1)
# making sure frame rate is set to 25
clip = core.std.AssumeFPS(clip=clip, fpsnum=25, fpsden=1)
clip = core.std.SetFrameProp(clip=clip, prop="_FieldBased", intval=0) # progressive
# changing range from limited to full range
clip = core.resize.Bicubic(clip, range_in_s="limited", range_s="full")
# Setting color range to PC (full) range.
clip = core.std.SetFrameProp(clip=clip, prop="_ColorRange", intval=0)
# adjusting color space from YUV420P8 to RGBS for vsVSGAN
clip = core.resize.Bicubic(clip=clip, format=vs.RGBS, matrix_in_s="470bg", range_s="full")
# resizing using VSGAN
from vsgan import ESRGAN
vsgan = ESRGAN(clip=clip,device="cuda")
model = "I:/Hybrid/64bit/vsgan_models/1x_Alias_200000_G.pth"
vsgan.load(model)
vsgan.apply() # 640x352
clip = vsgan.clip
# resizing 640x352 to 1280x704
# changing range from full to limited range
clip = core.resize.Bicubic(clip, range_in_s="full", range_s="limited")
# Setting color range to TV (limited) range.
clip = core.std.SetFrameProp(clip=clip, prop="_ColorRange", intval=1)
# adjusting resizing
clip = core.fmtc.resample(clip=clip, w=1280, h=704, kernel="lanczos", interlaced=False, interlacedd=False)
# adjusting output color from: RGBS to YUV420P8 for x264Model
clip = core.resize.Bicubic(clip=clip, format=vs.YUV420P8, matrix_s="470bg", range_s="limited", dither_type="error_diffusion")
# set output frame rate to 25fps (progressive)
clip = core.std.AssumeFPS(clip=clip, fpsnum=25, fpsden=1)
# Output
clip.set_output()
```
- tested it in vsViewer and with vspipe
=> both worked. :)
